---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(caret)
library(corrplot)
library(cowplot)
library(tidyverse)
```

## Read the data

```{r}
data_train<-fread('data/train.csv')
data_test<-fread("data/test.csv")
```

## EDA
```{r}
# Dimensions
dim(data_train)
names(data_train)

# Structure of Data Frame
str(data_train)
```

```{r}
combined_data<-rbind(data_train,data_test,fill=TRUE)

ggplot(data_train) + geom_histogram(aes(data_train$Item_Outlet_Sales),binwidth = 100) + xlab("Item Outlet Sales")

```

```{r}
p1 = ggplot(combined_data) + geom_histogram(aes(Item_Weight),binwidth = 0.5)
p2 = ggplot(combined_data) + geom_histogram(aes(Item_Visibility),binwidth = 0.005)
p3 = ggplot(combined_data) + geom_histogram(aes(Item_MRP),binwidth = 1)
plot_grid(p1,p2,p3,nrow=1)

```

```{r}
unique(combined_data$Item_Fat_Content)
combined_data$Item_Fat_Content[combined_data$Item_Fat_Content=='LF']='Low Fat'
combined_data$Item_Fat_Content[combined_data$Item_Fat_Content=='low fat']='Low Fat'
combined_data$Item_Fat_Content[combined_data$Item_Fat_Content=='reg']='Regular'

ggplot(combined_data %>% group_by(Item_Fat_Content) %>% summarise(Count = n())) +   geom_bar(aes(Item_Fat_Content, Count), stat = "identity")
```


```{r}
ggplot(combined_data %>% group_by(Item_Type) %>% summarise(Count=n())) + geom_bar(aes(Item_Type,Count),stat='identity') + geom_label(aes(Item_Type, Count, label = Count), vjust = 0.5) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(combined_data %>% group_by(Outlet_Identifier) %>% summarise(Count=n())) + geom_bar(aes(Outlet_Identifier,Count),stat='identity') + geom_label(aes(Outlet_Identifier, Count, label = Count), vjust = 0.5) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
ggplot(combined_data %>% group_by(Outlet_Size) %>% summarise(Count=n())) + geom_bar(aes(Outlet_Size,Count),stat='identity') + geom_label(aes(Outlet_Size, Count, label = Count), vjust = 0.5) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
ggplot(combined_data %>% group_by(Outlet_Establishment_Year) %>% summarise(Count=n())) + geom_bar(aes(Outlet_Establishment_Year,Count),stat='identity') + geom_label(aes(Outlet_Establishment_Year, Count, label = Count), vjust = 0.5) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
ggplot(combined_data %>% group_by(Outlet_Type) %>% summarise(Count=n())) + geom_bar(aes(Outlet_Type,Count),stat='identity') + geom_label(aes(Outlet_Type, Count, label = Count), vjust = 0.5) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```



## Bivariate Analysis

```{r}
p5 = ggplot(data_train) + geom_point(aes(Item_Weight, Item_Outlet_Sales), colour = "violet", alpha = 0.3) + theme(axis.title = element_text(size = 8.5))
p6 = ggplot(data_train) + geom_point(aes(Item_Visibility, Item_Outlet_Sales), colour = "violet", alpha = 0.3) + theme(axis.title = element_text(size = 8.5))
p7 = ggplot(data_train) + geom_point(aes(Item_MRP, Item_Outlet_Sales), colour = "violet", alpha = 0.3) + theme(axis.title = element_text(size = 8.5))

second_row=plot_grid(p6,p7,ncol=2)
plot_grid(p5,second_row,nrow = 2)
```

```{r}
p8 = ggplot(data_train) + geom_violin(aes(Item_Type, Item_Outlet_Sales), fill = "magenta") + theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text = element_text(size = 6), axis.title = element_text(size = 8.5))
p9 = ggplot(data_train) + geom_violin(aes(Item_Fat_Content, Item_Outlet_Sales), fill = "magenta") + theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text = element_text(size = 6), axis.title = element_text(size = 8.5))
p10 = ggplot(data_train) + geom_violin(aes(Outlet_Identifier, Item_Outlet_Sales), fill = "magenta") + theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text = element_text(size = 6), axis.title = element_text(size = 8.5))
second_row_3 = plot_grid(p9, p10, ncol = 2) 
plot_grid(p8, second_row_3, ncol = 1)
```

```{r}
p11 = ggplot(data_train) + geom_violin(aes(Outlet_Location_Type, Item_Outlet_Sales), fill = "magenta") 
p12 = ggplot(data_train) + geom_violin(aes(Outlet_Type, Item_Outlet_Sales), fill = "magenta") 
plot_grid(p11, p12, ncol = 1)

```



```{r}
is.na(combined_data)
apply(is.na(combined_data), 2, which)
```

## Handling Missing Values

```{r}
## Replacing Item Weight NULL values with mean
missing_index=which(is.na(combined_data$Item_Weight))

for (i in missing_index){
  item=combined_data$Item_Identifier[i]
  combined_data$Item_Weight[i]=mean(combined_data$Item_Weight[combined_data$Item_Identifier == item],na.rm=T)
}

## Replacing 0 values with mean values

zero_index = which(combined_data$Item_Visibility == 0) 
for(i in zero_index){    
  item = combined_data$Item_Identifier[i]  
  combined_data$Item_Visibility[i] = mean(combined_data$Item_Visibility[combined_data$Item_Identifier == item], na.rm = T) 
  }

```

## Feature Engineering

```{r}
## Grouping Item Type into broader categories
perishable = c("Breads", "Breakfast", "Dairy", "Fruits and Vegetables", "Meat", "Seafood")
non_perishable = c("Baking Goods", "Canned", "Frozen Foods", "Hard Drinks", "Health and Hygiene", "Household", "Soft Drinks")

combined_data[,Item_Type_new := ifelse(Item_Type %in% perishable, "perishable",ifelse(Item_Type %in% non_perishable,"non_perishable","not_sure"))]

```

```{r}
## Drinks -> DR, Food -> FD, Non-Consumable -> NC 
table(combined_data$Item_Type, substr(combined_data$Item_Identifier,1,2))

combined_data[,Item_category := substr(combined_data$Item_Identifier,1,2)]
```

```{r}
## Years of Operations for Outlets
combined_data[,Outlet_Years := 2013 - Outlet_Establishment_Year]
combined_data$Outlet_Establishment_Year = as.factor(combined_data$Outlet_Establishment_Year)

## Price Per weight
combined_data[,price_per_unit_wt := Item_MRP/Item_Weight]

## Create Item_MRP_Clusters
combined_data[,Item_MRP_clusters := ifelse(Item_MRP < 69, "1st",
                                  ifelse(Item_MRP >= 69 & Item_MRP < 136, "2nd",
                                  ifelse(Item_MRP >= 136 & Item_MRP < 203, "3rd", "4th")))]

```








